### ISSUE TITLE
Remove plugin updater class

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-coupon-importer#15]
We should only use the one in core.

**Comment by cklosowski** [comment]
Fixed this up, it's now using the `EDD_License` class, instead of `EDD_SL_Plugin_Updater` and I've moved the license key field to the Licenses tab @SDavisMedia. It also includes a migration routine that moves the data over so that it's included in the way the license key fields expect it to be.

**Comment by SDavisMedia** [comment]
Data moved over and shows up fine on the Licenses tab. :+1:
